ILLINOIS_ORANGE = '#FF5F05'  
ILLINOIS_BLUE = '#13294B'    
ILLINOIS_LIGHT_BLUE = '#1D58A7'  
ILLINOIS_GRAY = '#707372' 
ILLINOIS_LIGHT_GRAY = '#9C9A9D'
ILLINOIS_LIGHTEST_BLUE = '#009FD4' 
ILLINOIS_LIGHTEST_GRAY = '#C8C6C7'  

    # Custom color palette for multiple categories
ILLINOIS_COLORS = [ILLINOIS_ORANGE, ILLINOIS_BLUE, ILLINOIS_GRAY, ILLINOIS_LIGHT_BLUE, ILLINOIS_LIGHT_GRAY, ILLINOIS_LIGHTEST_BLUE, ILLINOIS_LIGHTEST_GRAY]